baseURL = ""
languageCode = "en-us"
title = "Quasar"
paginate = 5 #frontpage pagination

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/#features"
    weight = -130
